2021-11-28 20:44:04,855  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,855  INFO     Попытка очистки базы данных пользователей (main.py:173)
2021-11-28 20:44:04,862  WARNING  404 База данных питомцев пуста (crud.py:228)
2021-11-28 20:44:04,863  WARNING  404 База данных пользователей пуста (crud.py:224)
2021-11-28 20:44:04,864  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,870  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,870  INFO     Попытка создать пользователя с email: "test_email_1" (main.py:37)
2021-11-28 20:44:04,900  INFO     Пользователь c email: "test_email_1" и id = 1 создан (crud.py:26)
2021-11-28 20:44:04,902  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,909  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,909  INFO     Попытка создать пользователя с email: "test_email_1" (main.py:37)
2021-11-28 20:44:04,910  WARNING  400 Пользователь с таким email уже зарегистрирован (crud.py:202)
2021-11-28 20:44:04,911  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,916  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,916  INFO     Попытка добавления питомца по кличке "test_title_1" пользователю с id = "1" (main.py:47)
2021-11-28 20:44:04,942  INFO     Питомец по кличке "test_title_1" добавлен пользователю с id = 1 (crud.py:42)
2021-11-28 20:44:04,943  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,949  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,949  INFO     Попытка добавления питомца по кличке "test_title_1" пользователю с id = "1" (main.py:47)
2021-11-28 20:44:04,951  WARNING  400 У пользователя с id 1 уже есть питомец с такой кличкой и описанием (main.py:54)
2021-11-28 20:44:04,952  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,957  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,958  INFO     Попытка добавления питомца по кличке "test_title" пользователю с id = "99" (main.py:47)
2021-11-28 20:44:04,959  WARNING  404 Пользователь с id 99 не найден (crud.py:224)
2021-11-28 20:44:04,959  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,964  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,965  INFO     Попытка отобразить пользователя с id = 1 (main.py:72)
2021-11-28 20:44:04,966  INFO     Информация о пользователе с id = 1 предоставлена (main.py:75)
2021-11-28 20:44:04,967  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,973  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,973  INFO     Попытка отобразить пользователя с id = 88 (main.py:72)
2021-11-28 20:44:04,974  WARNING  404 Пользователь с id 88 не найден (crud.py:224)
2021-11-28 20:44:04,975  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,979  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,980  INFO     Попытка отобразить информацию о питомце по id хозяина = 1 и id животного = 77 (main.py:81)
2021-11-28 20:44:04,982  WARNING  404 Питомец по id хозяина = 1 и id животного = 77 не найден (crud.py:224)
2021-11-28 20:44:04,982  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,988  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,988  INFO     Попытка отобразить информацию о питомце по id хозяина = 66 и id животного = 1 (main.py:81)
2021-11-28 20:44:04,990  WARNING  404 Питомец по id хозяина = 66 и id животного = 1 не найден (crud.py:224)
2021-11-28 20:44:04,990  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:04,995  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:04,995  INFO     Попытка отобразить информацию о питомце по id хозяина = 1 и id животного = 1 (main.py:81)
2021-11-28 20:44:04,997  INFO     Информация о питомце по id хозяина = 1 и id животного = 1 предоставлена (main.py:84)
2021-11-28 20:44:04,998  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,003  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,004  INFO     Попытка добавления питомца по кличке "test_title_2" пользователю с id = "1" (main.py:47)
2021-11-28 20:44:05,027  INFO     Питомец по кличке "test_title_2" добавлен пользователю с id = 1 (crud.py:42)
2021-11-28 20:44:05,028  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,033  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,033  INFO     Попытка отобразить всех питомцев пользователя с id = 1 (main.py:90)
2021-11-28 20:44:05,035  INFO     Информация о питомцах пользователя с id = 1 предоставлена (main.py:94)
2021-11-28 20:44:05,036  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,041  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,041  INFO     Попытка отобразить всех питомцев пользователя с id = 55 (main.py:90)
2021-11-28 20:44:05,042  WARNING  404 У пользователя с id = 55 нет питомцев или пользователя с таким id не существует (crud.py:224)
2021-11-28 20:44:05,043  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,047  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,048  INFO     Попытка создать пользователя с email: "test_email_2" (main.py:37)
2021-11-28 20:44:05,070  INFO     Пользователь c email: "test_email_2" и id = 2 создан (crud.py:26)
2021-11-28 20:44:05,072  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,077  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,078  INFO     Попытка добавления питомца по кличке "test_title_2" пользователю с id = "2" (main.py:47)
2021-11-28 20:44:05,101  INFO     Питомец по кличке "test_title_2" добавлен пользователю с id = 2 (crud.py:42)
2021-11-28 20:44:05,102  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,107  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,107  INFO     Попытка отобразить всех питомцев в магазине (main.py:100)
2021-11-28 20:44:05,109  INFO     Информация о всех питомцах в магазине предоставлена (main.py:103)
2021-11-28 20:44:05,110  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,116  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,116  INFO     Попытка изменить информацию о пользователе с id = 1 (main.py:110)
2021-11-28 20:44:05,139  INFO     Информация о пользователе с id = 1 изменена (crud.py:130)
2021-11-28 20:44:05,139  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,145  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,145  INFO     Попытка изменить информацию о пользователе с id = 2 (main.py:110)
2021-11-28 20:44:05,147  WARNING  400 Пользователь с email: new_test_email_1 уже зарегистрирован (crud.py:202)
2021-11-28 20:44:05,148  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,154  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,154  INFO     Попытка изменить информацию о пользователе с id = 33 (main.py:110)
2021-11-28 20:44:05,155  WARNING  404 Пользователь с id 33 не найден (crud.py:224)
2021-11-28 20:44:05,156  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,161  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,161  INFO     Попытка изменить информацию о питомце по id хозяина = 77 и id животного = 1 (main.py:126)
2021-11-28 20:44:05,163  WARNING  404 Пользователь с id 77 не найден (crud.py:224)
2021-11-28 20:44:05,163  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,168  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,168  INFO     Попытка изменить информацию о питомце по id хозяина = 1 и id животного = 77 (main.py:126)
2021-11-28 20:44:05,170  WARNING  404 Питомец с таким id у данного пользователя не найден (crud.py:224)
2021-11-28 20:44:05,170  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,177  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,177  INFO     Попытка изменить информацию о питомце по id хозяина = 1 и id животного = 1 (main.py:126)
2021-11-28 20:44:05,192  INFO     Информация о питомце по id хозяина = 1 и id животного = 1 изменена (crud.py:149)
2021-11-28 20:44:05,192  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,198  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,199  INFO     Попытка изменить информацию о питомце по id хозяина = 1 и id животного = 2 (main.py:126)
2021-11-28 20:44:05,201  WARNING  400 У пользователя уже есть питомец с такой кличкой и описанием (crud.py:202)
2021-11-28 20:44:05,202  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,206  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,207  INFO     Попытка удаления все питомцев у пользователя с id = 1 (main.py:163)
2021-11-28 20:44:05,216  INFO     Питомец с id хозяина = 1 и id животного = 1 удален (crud.py:167)
2021-11-28 20:44:05,228  INFO     Питомец с id хозяина = 1 и id животного = 2 удален (crud.py:167)
2021-11-28 20:44:05,228  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,233  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,234  INFO     Попытка удаления питомца по id хозяина = 2 и id животного = 3 (main.py:153)
2021-11-28 20:44:05,247  INFO     Питомец с id хозяина = 2 и id животного = 3 удален (crud.py:167)
2021-11-28 20:44:05,248  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,253  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,253  INFO     Попытка удаления питомца по id хозяина = 1 и id животного = 77 (main.py:153)
2021-11-28 20:44:05,259  WARNING  404 Питомец с id хозяина = 1 и id животного = 77 не найден (crud.py:224)
2021-11-28 20:44:05,259  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,265  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,266  INFO     Попытка удаления питомца по id хозяина = 77 и id животного = 1 (main.py:153)
2021-11-28 20:44:05,267  WARNING  404 Питомец с id хозяина = 77 и id животного = 1 не найден (crud.py:224)
2021-11-28 20:44:05,268  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,273  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,273  INFO     Попытка удаления все питомцев у пользователя с id = 1 (main.py:163)
2021-11-28 20:44:05,274  WARNING  404 У пользователей с id = 1 нет питомцев или такого пользователя не существует (crud.py:224)
2021-11-28 20:44:05,275  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,280  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,281  INFO     Попытка удаления все питомцев у пользователя с id = 55 (main.py:163)
2021-11-28 20:44:05,282  WARNING  404 У пользователей с id = 55 нет питомцев или такого пользователя не существует (crud.py:224)
2021-11-28 20:44:05,283  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,288  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,288  INFO     Попытка удаления пользователя с id = 55 (main.py:142)
2021-11-28 20:44:05,290  WARNING  404 Пользователь с id = 55 не найден (crud.py:224)
2021-11-28 20:44:05,291  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,295  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,296  INFO     Попытка удаления пользователя с id = 1 (main.py:142)
2021-11-28 20:44:05,306  INFO     Пользователь с id = 1 удален (crud.py:163)
2021-11-28 20:44:05,306  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,311  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,311  INFO     Попытка очистки базы данных пользователей (main.py:173)
2021-11-28 20:44:05,317  WARNING  404 База данных питомцев пуста (crud.py:228)
2021-11-28 20:44:05,326  INFO     Пользователь с id = 2 удален (crud.py:163)
2021-11-28 20:44:05,326  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,332  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,332  INFO     Попытка очистки базы данных пользователей (main.py:173)
2021-11-28 20:44:05,338  WARNING  404 База данных питомцев пуста (crud.py:228)
2021-11-28 20:44:05,338  WARNING  404 База данных пользователей пуста (crud.py:224)
2021-11-28 20:44:05,339  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,344  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,344  INFO     Попытка создать пользователя с email: "test_email_3" (main.py:37)
2021-11-28 20:44:05,360  INFO     Пользователь c email: "test_email_3" и id = 1 создан (crud.py:26)
2021-11-28 20:44:05,361  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,367  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,367  INFO     Попытка отобразить всех питомцев в магазине (main.py:100)
2021-11-28 20:44:05,368  WARNING  404 База данных питомцев пуста (crud.py:224)
2021-11-28 20:44:05,369  DEBUG    Соединение с базой данных закрыто (main.py:31)
2021-11-28 20:44:05,374  DEBUG    Соединение с базой данных открыто (main.py:26)
2021-11-28 20:44:05,374  INFO     Попытка очистки базы данных пользователей (main.py:173)
2021-11-28 20:44:05,375  WARNING  404 База данных питомцев пуста (crud.py:228)
2021-11-28 20:44:05,383  INFO     Пользователь с id = 1 удален (crud.py:163)
2021-11-28 20:44:05,383  DEBUG    Соединение с базой данных закрыто (main.py:31)
